services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - .env

    container_name: outlook_app
    command: python src/app.py
    expose:
      - "8000"

  nginx:
    image: nginx
    container_name: outlook_nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/ssl:ro
    depends_on:
      - app